project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left:
      - text: Hands-on Exercises
        menu:
          - text: "1A: Data Wrangling with R"
            href: Hands-on_Ex1/Hands-on_Ex1A.qmd
          - text: "1B: Choropleth Mapping with R"
            href: Hands-on_Ex1/Hands-on_Ex1B.qmd
          - text: "2A: Spatial Weights and Applications"
            href: Hands-on_Ex2/Hands-on_Ex2A.qmd
          - text: "2B: Global Measures of Spatial Autocorrelation"
            href: Hands-on_Ex2/Hands-on_Ex2B.qmd
          - text: "2C: Local Measures of Spatial Autocorrelation"
            href: Hands-on_Ex2/Hands-on_Ex2C.qmd
      - text: In-class Exercises
        menu:
          - text: In-class Exercise 1
            href: In-class_Ex1/In-class_Ex1.qmd
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: zephyr
    css: styles.css
    toc: true

editor: visual

